### ISSUE TITLE
Can't drag window around

### ISSUE THREAD

**Issue by silouanwright** [jaredculp/iterm2-borderless-padding#3]
I'm sure you know this, but the window can't be dragged around with the mouse. I'm not an Xcode developer but I have to assume it's possible.

**Comment by silouanwright** [comment]
http://stackoverflow.com/questions/7287696/moving-borderless-nswindow-fully-covered-with-web-view
http://www.cocoabuilder.com/archive/cocoa/129590-moving-borderless-window.html

Just googling for something that might be useful

**Comment by leifniem** [comment]
For me it works if i place the mouse on the top border so that the scale icon shows, and move 1-2 pixels up before i drag. Or if you're on a MacBook, just use 3-finger-drag on trackpad.

**Comment by jgillman** [comment]
It's not free (any more), but [Better Touch Tool](https://www.boastr.net/) has an option where you can set a modifier key + mouse move to move or resize a window. (screenshot below)

If anyone knows of a program that enables _just_ that one feature I would love to know!

![screen shot 2016-02-08 at 11 40 39 am](https://cloud.githubusercontent.com/assets/172217/12896822/f156fb44-ce58-11e5-94ea-7f9177be2226.png)

**Comment by ghost** [comment]
If you have some patience and can get [Hammerspoon](http://www.hammerspoon.org/) set up, it amounts to a huge time savings. This issue is also solved since you can use key bindings to move your windows around.

If you need a quick configuration, there are lots of [examples](https://github.com/Hammerspoon/hammerspoon/wiki/Sample-Configurations). Here are my [keybindings](https://github.com/asethwright/dotfiles/blob/master/hammerspoon/init.lua).

Hope this helps.

**Comment by megalithic** [comment]
@asethwright i love hammerpsoon soo much.

**Comment by jaredculp** [comment]
This functionality now lives upstream, so repo is now deprecated, see README.
